apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: myapp-secrets
spec:
  # Specific namespaces
  namespaces:
    - my-app
    - nginx-app
    - redis-app
  
  # Or use label selector
  # namespaceSelectors:
  #   - matchLabels:
  #       needs-secrets: "true"

  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      name: myapp-secrets
      creationPolicy: Owner
    data:
      - secretKey: username
        remoteRef:
          key: myapp/config
          property: username
      - secretKey: password
        remoteRef:
          key: myapp/config
          property: password
      - secretKey: api-key
        remoteRef:
          key: myapp/config
          property: api-key
